name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Tests
        run: |
          set -o pipefail && xcodebuild clean build test \
            -project Appointment/Appointment.xcodeproj \
            -scheme Appointment \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" \
            -configuration Debug \
            -enableCodeCoverage YES \
            -derivedDataPath "./DerivedData" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO;